version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress-data:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    container_name: mariadb
    image: mariadb
    restart: always
    env_file: .env
    networks:
      - inception
  
volumes:
  wordpress-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dongseo/data/wordpress'

  mariadb-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dongseo/data/mariadb'

networks:
  inception: